name: Create Release

on:
  workflow_run:
    workflows: ["Build Windows Executable"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd bin
          npm install
      
      - name: Make scripts executable
        run: |
          chmod +x ./bin/github_release.ts
          chmod +x ./bin/download_artifacts.ts
      
      - name: Download artifacts
        id: download_artifacts
        run: |
          cd bin
          npm install
          npx tsx ./download_artifacts.ts "${{ secrets.GITHUB_TOKEN }}" "${{ github.repository_owner }}" "${{ github.event.repository.name }}" ${{ github.event.workflow_run.id }}
      
      - name: List files
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Files in bin directory:"
          ls -la bin
          echo "Files in artifacts directory (if exists):"
          ls -la artifacts || echo "No artifacts directory"
      
      - name: Create GitHub Release
        run: |
          cd bin
          npm install
          npx tsx ./github_release.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_TAG: ${{ steps.download_artifacts.outputs.is_tag }}
          TAG_NAME: ${{ steps.download_artifacts.outputs.tag_name }}
          RELEASE_NAME: ${{ steps.download_artifacts.outputs.release_name }}
          ALSO_TAG_AS_LATEST: ${{ steps.download_artifacts.outputs.also_tag_as_latest }}
